stages:
  - build

build_job:
  stage: build
  image: harbor.exayun.org/public/docker:20.10.7
  script:
    - IMG=harbor.exayun.org/c-base/devops_build:1.0.0
    - docker login -u yhc -p ${dockerlogin} harbor.exayun.org
    - docker build -t $IMG -f Dockerfile .
    - docker push $IMG
